### ISSUE TITLE
Server side crash (True shot)

### ISSUE THREAD

**Issue by damix96** [Tfarcenim/RandomEnchantments#11]
server crashes when shooting with true shot
[latest.log](https://github.com/Tfarcenim/RandomEnchantments/files/3265609/latest.log)

**Comment by Tfarcenim** [comment]
Can you use pastebin? My phone can't open it

**Comment by damix96** [comment]
sry
https://pastebin.com/QmRfnJ4L

**Comment by Tfarcenim** [comment]
resolved in 0.1.1b.
