### ISSUE TITLE
Suggestion: Compatibility with Extra Bows Mod

### ISSUE THREAD

**Issue by AwesomeNinja886** [Tfarcenim/RandomEnchantments#12]
As of now, the mod doesn't work with the [Extra Bows Mod](https://www.curseforge.com/minecraft/mc-mods/extra-bows). With it enabled, even the Vanilla bow's custom enchantments don't work right. I feel there should be compatibility with the mod because it allows for a whole new realm of possibility. Plus it fixes a bug (you can't use any of the bow enchantments with ExtraBows installed). Two birds with one <del>stone</del> arrow, huh? (lol)

**Comment by Tfarcenim** [comment]
for which mc version?

**Comment by AwesomeNinja886** [comment]
> for which mc version?

1.14.3 (Forge preferably, but it also has a Fabric version for 1.14.3)

**Comment by Tfarcenim** [comment]
I'm using it just fine
![image](https://user-images.githubusercontent.com/44327798/61343436-bd98c580-a81b-11e9-90d0-7710a3a5575e.png) this is with only extra bows and random enchants installed.

**Comment by AwesomeNinja886** [comment]
I can enchant the item, but the bow itself doesn't use the mechanics of the enchantment. It may also have something to do with the fact that I changed the key to upgrade the bow from B to P so it was compatible with Xaero's World Map.

**Comment by AwesomeNinja886** [comment]
Like, I enchanted a bow with Torches and it didn't place torches. It may also be because I was in Creative.

**Comment by AwesomeNinja886** [comment]
My full list of mods:

Gobber 2
Extra Bows
Engineer's Decor
Random Enchants
Super Tools
Tubes Reloaded
Biomes O' Plenty
CC: Tweaked
The One Probe
Xaero's Minimap
Xaero's World Map
Better Storage Too
Mob Catcher
minecraftcapes.co.uk
Weapon Craftery
ToLaserBlade
Wetstone

**Comment by Tfarcenim** [comment]
Torches indeed wasn't working, but it's fixed now

**Comment by Tfarcenim** [comment]
seems like all nonconflicting enchants work now, closing as resolved
