### ISSUE TITLE
Is it possible to have it configurable?

### ISSUE THREAD

**Issue by trukulo** [Tfarcenim/RandomEnchantments#14]
I was thinking about probabilities of things like lightning, enable or disable enchantments, and...

Well, as a bonus track, i think you are too focused in swords and bows (just my humble opinion, of course!).

- Is it possible to change some spells and make them for other weapons?  Like Disarm and Paralysis for axes, Homecoming, Phase and lightning for crossbows, Teleportation and Cursed Jumping for Trident, True Lifesteal only for sword. Deflect should for shields.

- Back to the chamber should have 10% per level, otherwise is better than infinite in level V, as it can be used with mending.
- Solar should conflict with mending.

Er... I'm sorry if i ask for too much, but if you can use any of these ideas... It's just trying to make it more balanced for a long term experience in game.

**Comment by Tfarcenim** [comment]
adding more enchantment enums is easy, as for configurability of the enchant itself, I'll look into that
