### ISSUE TITLE
Biomes o Plenty

### ISSUE THREAD

**Issue by ImJustANeutron** [Tfarcenim/RandomEnchantments#15]
So i was looking for mod to play in the version 1.14.4 and i downloaded like 50 of them, one of them was this mod that looks great yknow just adds random enchantments so i downloaded it, but when i was going to play for some reason i was unable to select the biomes o plenty terrain generator so i thought that was some other biome mod, and after i tested all the mods to see what was the mod causing the issue i found that is this one so i was surprised because this mod is unrelated to the biomes o plenty mod. i hope you fix the issue.
i was using the 2.1.0 vesion of random enchantments and the 9.0.0.231 version of biomes o plenty

**Comment by Tfarcenim** [comment]
crash has been fixed
