### ISSUE TITLE
Please improve Enchantment Descriptions support

### ISSUE THREAD

**Issue by IdrisQe** [Tfarcenim/RandomEnchantments#18]
Enchantment descriptions are meant to be descriptive.
Currently, not only does Fast Place (whatever that is) not have a description, the current descriptions are... _Less than ideal._ The whole reason I installed Enchantment Descriptions was so I _wouldn't_ need to refer to the mod's curseforge page any time I wanted to enchant something.
References and memes are fine and dandy, but I'd much rather have solid descriptions like the vanilla ones, and ones added by most other mods.

**Comment by Tfarcenim** [comment]
not rewriting them for a second time
