### ISSUE TITLE
[Question / Concern] Do Trueshot Arrows ever Despawn?

### ISSUE THREAD

**Issue by TeetoKaziim** [Tfarcenim/RandomEnchantments#2]
![image](https://user-images.githubusercontent.com/25490944/56703154-41379000-66cd-11e9-9d4e-435d99402d10.png)

I worry, slightly, though not much, especially about trueshot phasing arrows under the bedrock, way up in the sky, or hiding inside of the terrain, forever, doing whatever it is arrows do with tick time. (Each one appears to be about donkey's-worth of tick time!)

![image](https://user-images.githubusercontent.com/25490944/56703357-008c4680-66ce-11e9-8b76-202500d4348a.png)

While this isn't that much tick time, admittedly... but, one could end up with a silly number of arrow entities in one's world, if one isn't the best marksman. On the upside, the ones that make it to -65Y get eaten by void damage, so at least there's that!

**Comment by Tfarcenim** [comment]
arrows should no longer hang around after 0.0.7a since I restricted their lifetime to 60 seconds.

**Comment by Tfarcenim** [comment]
Also the arrow tick time is sharply reduced now thanks to a rewrite of the homing algorithim.

**Comment by TeetoKaziim** [comment]
I don't know how to tell you this without seeming awful, but it seems like, even still in 0.0.8, that true shot arrows just hang in mid-air forever. And, if you don't put away your ricochet bow, those bounce forever as well. Which is adorable, and fun, but probably not what you want.

I was meaning to try out the new enchantments and come back here and close this but... I guess I'm just making more trouble. Good luck though.

**Comment by TeetoKaziim** [comment]
Tested in 0.0.10: Appears fixed. :D
