### ISSUE TITLE
Instant Death Issue?

### ISSUE THREAD

**Issue by Nelly1234567** [Tfarcenim/RandomEnchantments#20]
The enchant "Instant Death" seems to delete all items in a players or mobs inventory. With a mod like Corail Tombstone, it doesn't spawn a grave. It also doesn't show any death messages.

I will continue testing but as far as I can tell, it shouldn't be able to do that and is not supposed to according to the description and all sources I can find.

**Comment by Tfarcenim** [comment]
odd, it should just be setting the targets health to 0, I don't see how that would cause item deletion.

**Comment by Tfarcenim** [comment]
closed due to lack of activity

**Comment by Bass2style** [comment]
tread is now closed, but i have found the same issue on 1.12.2, it seems to affect only hostile mobs, both vanilla and modded mobs are affected, passive mobs seems to drop their loot, but hostiles ones not.

i should try if on 1.15 the problem persists, but i have issues with mods in 1.14+, so its a bit complicated for me to try out.

how can i help more to find out what is causing this ?

**Comment by Tfarcenim** [comment]
test it in a vanilla only environment and see if it still happens.

**Comment by Bass2style** [comment]
i will try this when i'm back home, and give my feedback asap.

**Comment by Yourname942** [comment]
This issue is happening for us still..
