### ISSUE TITLE
Crash while mining

### ISSUE THREAD

**Issue by BrisingrAerowing** [Tfarcenim/RandomEnchantments#23]
[Crash Log](https://gist.github.com/BrisingrAerowing/c4dbda0c765110ddf1fa899d614d155f)

Happened while mining a coal vein. Might be caused by OreExcavation (which I had active at the time).

**Comment by Tfarcenim** [comment]
hmm, was the tool enchanted with global traveller or anything else by any chance?

**Comment by BrisingrAerowing** [comment]
Yes. I had Global Traveler on it. Wasn’t using it, as I was still trying to find a decent village to settle in.

**Comment by Tfarcenim** [comment]
alright, found the issue
