### ISSUE TITLE
[1.12.2] Bug with Magnetic Enchantment

### ISSUE THREAD

**Issue by BrisingrAerowing** [Tfarcenim/RandomEnchantments#24]
I have a fortune ores mod installed (makes ores like Iron drop chunks affected by fortune), and with the Magnetic enchantment from this mod, I get the ore block in addition to the chunks. This also affects things like Shulker Shells (a mod I have makes them drop 2, but I get 3). I'm going to do more testing.

I'm not sure if this affects 1.14+ as well.

**Comment by Tfarcenim** [comment]
which mod is this

**Comment by BrisingrAerowing** [comment]
[How Fortunate!](https://www.curseforge.com/minecraft/mc-mods/how-fortunate)
