### ISSUE TITLE
Crash with randomenchants-3.1.0

### ISSUE THREAD

**Issue by ChromaPIE** [Tfarcenim/RandomEnchantments#28]
At first I thought it was cause by Flux Network, so I post an issue to their repository:

https://github.com/SonarSonic/Flux-Networks/issues/362

Chatting in the discord with the developers, the problem was still unclear, so I tried to remove the mods one by one and finally caught the suspect randomenchants-3.1.0.

All of the necessary informations are in the issue above.

Thank you very much.

**Comment by Tfarcenim** [comment]
> [20Apr2020 17:04:32.317] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: randomenchants, class com.tfar.randomenchants.RandomEnchants
java.lang.NoClassDefFoundError: com/tfar/additionalevents/event/DropLootEvent

go grab Additional Events, it's a required dependency.
