### ISSUE TITLE
Back to the Chamber only works on 1 type of arrow

### ISSUE THREAD

**Issue by CalaMariGold** [Tfarcenim/RandomEnchantments#29]
Back to the Chamber doesn't work on any arrows that aren't default vanilla. This includes the spectral arrows from vanilla, Better With Addons' great arrow, Spartan Weaponry's iron/diamond arrows, etc...

**Comment by Tfarcenim** [comment]
does this happen in 1.15?

**Comment by CalaMariGold** [comment]
1.12.2, sorry

**Comment by CalaMariGold** [comment]
Any updates on this?

**Comment by democat3457** [comment]
can be closed.
