### ISSUE TITLE
Still getting Disabled and Anviled enchantments.

### ISSUE THREAD

**Issue by ExZha1337** [Tfarcenim/RandomEnchantments#3]
I enchant the books by using the Enchantment Factory from (Industrial Foregoing). I have also tested it by using a normal vanilla Enchantment Table, and i still get them.

Heres my config file.
`# Configuration file

general {
    # Prevents disabled enchantments from being registered, use with caution
    B:"Nuclear Option"=false

    ##########################################################################################################
    # weapons
    #--------------------------------------------------------------------------------------------------------#
    # Combat Enchantment Config
    ##########################################################################################################

    weapons {
        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable 2 Lifesteal"=ANVIL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Back to the chamber"=DISABLED

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Combo"=ANVIL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Cursed Jumping"=ANVIL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Deflect"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Disarm"=ANVIL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Floating"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Homing"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Instant Death"=ANVIL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Lightning"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Paralysis"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Phasing"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Quickdraw"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Solar"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Teleportation"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Teleposistion"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable True Shot"=NORMAL
    }

    ##########################################################################################################
    # tools
    #--------------------------------------------------------------------------------------------------------#
    # Tool Enchantment Config
    ##########################################################################################################

    tools {
        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Equal Mine"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Grappling"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Lumberjack"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Momentum"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Obsidian Buster"=DISABLED

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Randomness"=ANVIL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Snatching"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Stonebound"=NORMAL

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Stonelover"=NORMAL
    }

    ##########################################################################################################
    # curses
    #--------------------------------------------------------------------------------------------------------#
    # Curse Enchantment Config
    ##########################################################################################################

    curses {
        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Breaking"=DISABLED

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Butterfingers"=DISABLED

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Fumbling"=DISABLED

        # Valid values:
        # DISABLED
        # ANVIL
        # NORMAL
        S:"Enable Shadow"=DISABLED
    }

**Comment by Tfarcenim** [comment]
try in 0.0.7b and see if it's resolved.

**Comment by Tfarcenim** [comment]
I'm going to take the lack of response as an it's fixed.

**Comment by ExZha1337** [comment]
Sorry for not responding, after i posted that my harddrives fried. So i haven't been able to check.
