### ISSUE TITLE
(Forge 1.15.2) Disabling enchants in TOML file doesn't stop the enchant to appear in chests/mob drops/villagers' trade.

### ISSUE THREAD

**Issue by intemptesta** [Tfarcenim/RandomEnchantments#36]
I'm using Random Enchants 3.1.0 for Forge 1.15.2 server.

I really like those added enchants, they're fun to use. But some of them are too OP for our server (instant death etc.)

I tried to edit the TOML config file and set those enchants to DISABLED. This seem to stop them from appearing on enchanting table, but they still have a chance to appear as chest loot, enchanted mob drops, or as librarian villagers' trade.

I'd like to request a way to disable selwcted enchants entirely from the server. Thank you.

**Comment by Tfarcenim** [comment]
https://www.curseforge.com/minecraft/mc-mods/enchantment-control can do it
