### ISSUE TITLE
Disabling enchantments in the config should disable those enchantments

### ISSUE THREAD

**Issue by yukinagatosc2** [Tfarcenim/RandomEnchantments#38]
Currently when enchantments are disabled in the config, they are not unregistered but instead lore is added that says this enchantment is disabled.  These "disabled" enchantments still function just as well as if they were not disabled.  The only way that I have found to disable these enchantments is through the use of external mods but this is tedious and unreliable.

**Comment by Tfarcenim** [comment]
They cannot be safely unregistered anymore due to registry shifting, if you still have issues with them showing up in loot tables, use Enchantment Control.
