### ISSUE TITLE
Probable Crash

### ISSUE THREAD

**Issue by Taccio33** [Tfarcenim/RandomEnchantments#4]
not sure if it is this mod, but going back to 0.7 seems to fix the crash
(quick question: does the instant kill remove loot from the killed entity?)

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2019-04-27 21:17:32 CEST
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
    at com.tfar.randomenchantments.ench.enchantment.EnchantmentQuickdraw.<clinit>(EnchantmentQuickdraw.java:71)
    at com.tfar.randomenchantments.init.ModEnchantment.<clinit>(ModEnchantment.java:47)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_451_ModEnchantment_registerEnchantments_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3930)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1120777288 bytes (1068 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 133 mods loaded, 133 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version          | Source                                              | Signature                                |
       |:----- |:--------------------------------- |:---------------- |:--------------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft                         | 1.12.2           | minecraft.jar                                       | None                                     |
       | UCH   | mcp                               | 9.42             | minecraft.jar                                       | None                                     |
       | UCH   | FML                               | 8.0.99.99        | forge-1.12.2-14.23.5.2768.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | forge                             | 14.23.5.2768     | forge-1.12.2-14.23.5.2768.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCH   | foamfixcore                       | 7.7.4            | minecraft.jar                                       | None                                     |
       | UCH   | yac                               | 2.2.003          | YetAnotherCore-2.2.003-MC1.12.2.jar                 | None                                     |
       | UCH   | forgelin                          | 1.6.0            | Forgelin-1.6.0.jar                                  | None                                     |
       | UCH   | alib                              | 1.0.4            | alib-1.0.4.jar                                      | None                                     |
       | UCH   | jei                               | 4.15.0.273       | jei_1.12.2-4.15.0.273.jar                           | None                                     |
       | UCH   | appleskin                         | 1.0.9            | AppleSkin-mc1.12-1.0.9.jar                          | None                                     |
       | UCH   | baubles                           | 1.5.2            | Baubles-1.12-1.5.2.jar                              | None                                     |
       | UCH   | artifacts                         | 1.12.2-1.0.2     | Artifacts-1.12.2-1.0.2.jar                          | None                                     |
       | UCH   | projecte                          | 1.12.2-PE1.4.0   | ProjectE-1.12.2-PE1.4.0.jar                         | None                                     |
       | UCH   | auxiliumequivalence               | 1.12.2-1.3.1     | auxiliumequivalence-1.12.2-1.3.1.jar                | None                                     |
       | UCH   | codechickenlib                    | 3.2.2.353        | CodeChickenLib-1.12.2-3.2.2.353-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | avaritia                          | 3.3.0            | Avaritia-1.12.2-3.3.0.33-universal.jar              | None                                     |
       | UCH   | endercore                         | 1.12.2-0.5.52    | EnderCore-1.12.2-0.5.52.jar                         | None                                     |
       | UCH   | enderio                           | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | avaritiaio                        | 1.1              | avaritiaio-1.2.jar                                  | None                                     |
       | UCH   | baubleofundying                   | 1.0.1            | BaubleOfUndying-1.12-1.0.1.jar                      | None                                     |
       | UCH   | baubleshulkerboxes                | 4r               | BaubleShulkerBoxes-1.12.2-4r.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCH   | bookshelf                         | 2.3.574          | Bookshelf-1.12.2-2.3.574.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | redstoneflux                      | 2.1.0            | RedstoneFlux-1.12-2.1.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCH   | brandonscore                      | 2.4.9            | BrandonsCore-1.12.2-2.4.9.195-universal.jar         | None                                     |
       | UCH   | sonarcore                         | 5.0.19           | sonarcore-1.12.2-5.0.19-20.jar                      | None                                     |
       | UCH   | calculator                        | 5.0.11           | calculator-1.12.2-5.0.11-12.jar                     | None                                     |
       | UCH   | chameleon                         | 1.12-4.1.3       | Chameleon-1.12-4.1.3.jar                            | None                                     |
       | UCH   | chanceglobe                       | v1.1             | chanceglobe-1.12.2-v1.1.jar                         | None                                     |
       | UCH   | chickenchunks                     | 2.4.1.73         | ChickenChunks-1.12.2-2.4.1.73-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | chickens                          | 6.1.0            | chickens-6.1.0.jar                                  | None                                     |
       | UCH   | coffeespawner                     | 1.0.2            | CoffeeSpawner-1.12-1.0.2.jar                        | None                                     |
       | UCH   | refinedstorage                    | 1.6.14           | refinedstorage-1.6.14.jar                           | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | UCH   | compactmachines3                  | 3.0.17           | compactmachines3-1.12.2-3.0.17-b267.jar             | None                                     |
       | UCH   | cucumber                          | 1.1.3            | Cucumber-1.12.2-1.1.3.jar                           | None                                     |
       | UCH   | darkutils                         | 1.8.223          | DarkUtils-1.12.2-1.8.223.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | deepmoblearning                   | 1.12.2-2.4.1     | deepmoblearning-1.12.2-2.4.1-universal.jar          | None                                     |
       | UCH   | denseneutroncollectors            | @VERSION@        | denseneutroncollectors-1.1.jar                      | None                                     |
       | UCH   | draconicevolution                 | 2.3.19           | Draconic-Evolution-1.12.2-2.3.19.330-universal.jar  | None                                     |
       | UCH   | draconicadditions                 | 1.0              | Draconic-Additions-1.12.2-1.7.1.17-universal.jar    | None                                     |
       | UCH   | durabilityviewer                  | 1.4              | DurabilityViewer-1.12-forge14.21.1.2387-1.4.jar     | None                                     |
       | UCH   | elevatorid                        | 1.3.8            | ElevatorMod-1.12.2-1.3.8.jar                        | None                                     |
       | UCH   | eplus                             | 5.0.176          | EnchantingPlus-1.12.2-5.0.176.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | enderiointegrationtic             | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderiobase                       | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderioconduits                   | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderioconduitsappliedenergistics | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderioconduitsopencomputers      | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderioconduitsrefinedstorage     | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderiointegrationforestry        | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderiointegrationticlate         | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderiomachines                   | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderiopowertools                 | 5.0.43           | EnderIO-1.12.2-5.0.43.jar                           | None                                     |
       | UCH   | enderioendergy                    | 5.0.43           | EnderIO-endergy-1.12.2-5.0.43.jar                   | None                                     |
       | UCH   | enderstorage                      | 2.4.5.135        | EnderStorage-1.12.2-2.4.5.135-universal (1).jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | entangled                         | 1.1.1            | entangled-1.1.1.jar                                 | None                                     |
       | UCH   | valkyrielib                       | 1.12.2-2.0.20.1  | valkyrielib-1.12.2-2.0.20.1.jar                     | None                                     |
       | UCH   | environmentaltech                 | 1.12.2-2.0.20.1  | environmentaltech-1.12.2-2.0.20.1.jar               | None                                     |
       | UCH   | hammercore                        | 2.0.4.4          | HammerCore-1.12.2-2.0.4.4.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCH   | equivadditions                    | 5r               | EquivalentAdditions-1.12.2-5r.jar                   | None                                     |
       | UCH   | eqs                               | 1.0.2            | EquivalentStorage-1.0.2.jar                         | None                                     |
       | UCH   | exnihilocreatio                   | 1.12.2-0.3.9     | exnihilocreatio-1.12.2-0.3.9.jar                    | None                                     |
       | UCH   | excompressum                      | 3.0.26           | ExCompressum_1.12.2-3.0.26.jar                      | None                                     |
       | UCH   | expequiv                          | 11b              | ExpandedEquivalence-1.12.2-11b.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCH   | exponentialpower                  | 1.4.1            | ExponentialPower-1.4.1.jar                          | None                                     |
       | UCH   | extrautils2                       | 1.0              | extrautils2-1.12-1.9.9.jar                          | None                                     |
       | UCH   | ezstorage                         | 2.5.0            | ezstorage-2.5.0-%5b1.12.2%5d.jar                    | None                                     |
       | UCH   | felling                           | 1.4.1            | felling-1.4.1-1.12.x.jar                            | None                                     |
       | UCH   | fluxnetworks                      | 3.0.19           | fluxnetworks-1.12.2-3.0.19-21.jar                   | None                                     |
       | UCH   | foamfix                           | 0.10.3-1.12.2    | foamfix-0.10.3-1.12.2.jar                           | None                                     |
       | UCH   | forgemultipartcbe                 | 2.6.0.79         | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | microblockcbe                     | 2.6.0.79         | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | None                                     |
       | UCH   | minecraftmultipartcbe             | 2.6.0.79         | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | None                                     |
       | UCH   | futureminecraft                   | 1.1              | FutureMinecraftV1.1.jar                             | None                                     |
       | UCH   | placebo                           | 1.5.1            | Placebo-1.12.2-1.5.1.jar                            | None                                     |
       | UCH   | growablecells                     | 3.1.0            | Growable+Cells-1.12.2-3.1.0.jar                     | None                                     |
       | UCH   | ichunutil                         | 7.2.0            | iChunUtil-1.12.2-7.2.0.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | UCH   | improvableskills                  | 3.6.2r           | ImprovableSkills-1.12.2-3.6.2r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCH   | teslacorelib                      | 1.0.15           | tesla-core-lib-1.12.2-1.0.15.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | industrialforegoing               | 1.12.2-1.12.2    | industrialforegoing-1.12.2-1.12.10-234.jar          | None                                     |
       | UCH   | mysticalagriculture               | 1.7.3            | MysticalAgriculture-1.12.2-1.7.3.jar                | None                                     |
       | UCH   | mysticalagradditions              | 1.3.1            | MysticalAgradditions-1.12.2-1.3.1.jar               | None                                     |
       | UCH   | mcjtylib_ng                       | 3.1.1            | mcjtylib-1.12-3.1.1.jar                             | None                                     |
       | UCH   | rftools                           | 7.61             | rftools-1.12-7.61.jar                               | None                                     |
       | UCH   | integrationforegoing              | 1.12.2-1.9       | IntegrationForegoing-1.12.2-1.9.jar                 | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | UCH   | itemfilters                       | 1.0.3.12         | ItemFilters-1.0.3.12.jar                            | None                                     |
       | UCH   | jaopcaagriculture                 | 1.12.2-1.2.1.13  | JAOPCAAgriculture-1.12.2-1.2.1.13.jar               | None                                     |
       | UCH   | jaopcasingularities               | 1.12.2-2.2.0.9   | JAOPCASingularities-1.12.2-2.2.0.9.jar              | None                                     |
       | UCH   | jaopca                            | 1.12.2-2.2.8.101 | JAOPCA-1.12.2-2.2.8.101.jar                         | None                                     |
       | UCH   | oredictinit                       | 1.12.2-2.2.1.71  | JAOPCA-1.12.2-2.2.8.101.jar                         | None                                     |
       | UCH   | jeresources                       | 0.8.10.50        | JustEnoughResources-1.12.2-0.8.10.50.jar            | None                                     |
       | UCH   | moreavaritia                      | 3.2              | moreavaritia-mc1.12.2-v3.2.jar                      | None                                     |
       | UCH   | morechickens                      | 3.1.0            | morechickens-1.12.2-3.1.0.jar                       | None                                     |
       | UCH   | recipehandler                     | 0.12             | NoMoreRecipeConflict-0.12(1.12.2).jar               | None                                     |
       | UCH   | notenoughwands                    | 1.7.3            | notenoughwands-1.12-1.7.3.jar                       | None                                     |
       | UCH   | nvlstorageblocks                  | 1.12.2.2768.4    | nvlstorageblocks-1.12.2.2768.4.jar                  | None                                     |
       | UCH   | octahedroid                       | 1.0.3            | octahedroid-1.0.3.jar                               | None                                     |
       | UCH   | omg_utilities                     | beta 1.1.0       | omg_utilities-1.12-beta+1.1.0.jar                   | None                                     |
       | UCH   | omlib                             | 3.1.0-229        | omlib-1.12.2-3.1.0-229.jar                          | None                                     |
       | UCH   | openmodularturrets                | 3.1.0-331        | openmodularturrets-1.12.2-3.1.0-331.jar             | None                                     |
       | UCH   | oversaturation                    | 1.1              | Oversaturation-1.1.jar                              | None                                     |
       | UCH   | teslathingies                     | 1.0.15           | powered-thingies-1.12.2-1.0.15.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCH   | projectex                         | 1.1.0.33         | ProjectEX-1.1.0.33.jar                              | None                                     |
       | UCH   | reborncore                        | 3.13.3.416       | RebornCore-1.12.2-3.13.3.416-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | UCH   | quantumstorage                    | 4.6.8            | QuantumStorage-1.12-4.6.8.jar                       | None                                     |
       | UCH   | randomenchantments                | @VERSION@        | randomenchantments-0.0.7b.jar                       | None                                     |
       | UCH   | rebornstorage                     | 1.0.0            | RebornStorage-1.12.2-3.3.2.79.jar                   | None                                     |
       | UCH   | refined_avaritia                  | 2.6              | refined_avaritia-1.12.2-2.6.jar                     | None                                     |
       | UCH   | refinedexchange                   | 2.1.1            | refinedexchange-2.1.1.jar                           | None                                     |
       | UCH   | refinedstorageaddons              | 0.4.4            | refinedstorageaddons-0.4.4.jar                      | None                                     |
       | UCH   | resourcehogs                      | 1.0.11           | ResourceHogs-1.12.2-1.0.11.jar                      | None                                     |
       | UCH   | roost                             | 2.0.10           | roost-1.12.2-2.0.10.jar                             | None                                     |
       | UCH   | rsinfinitewireless                | 1.2              | rsinfinitewireless-1.2.jar                          | None                                     |
       | UCH   | simplegenerators                  | 1.12.2-2.0.20.2  | simplegenerators-1.12.2-2.0.20.2.jar                | None                                     |
       | UCH   | simplybedrock                     | 1.2              | SimplyBedrock_V1.2.jar                              | None                                     |
       | UCH   | solarflux                         | 4.32r            | SolarFluxReborn_1.12.2-4.32r.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCH   | wearsfr                           | 17r              | SolarFluxAdditions-1.12.2-17r.jar                   | None                                     |
       | UCH   | storagedrawers                    | 1.12-5.3.5       | StorageDrawers-1.12.2-5.3.8.jar                     | None                                     |
       | UCH   | sync                              | 7.1.0            | Sync-1.12.2-7.1.0.jar                               | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | UCH   | tesslocator                       | 1.0.0.6          | Tesslocator-1.0.0.6.jar                             | None                                     |
       | UCH   | theoneprobe                       | 1.4.28           | theoneprobe-1.12-1.4.28.jar                         | None                                     |
       | UCH   | tinymobfarm                       | 1.0.5            | TinyMobFarm-1.12.2-1.0.5.jar                        | None                                     |
       | UCH   | tp                                | 3.2.32           | tinyprogressions-1.12.2-3.3.32-Release.jar          | None                                     |
       | UCH   | toolbelt                          | 1.7.1            | ToolBelt-1.12.0-1.7.1.jar                           | None                                     |
       | UCH   | torchmaster                       | 1.7.0.72         | torchmaster_1.12.2-1.7.0.72.jar                     | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | UCH   | translocators                     | 2.5.1.77         | Translocators-1.12.2-2.5.1.77-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | uteamcore                         | 2.0.2.86         | u_team_core-1.12.2-2.0.2.86.jar                     | None                                     |
       | UCH   | ultimatecobblegen                 | 1.3              | Ultimate+SkyBlock+Resource+Generator-1.12.2-1.3.jar | None                                     |
       | UCH   | utilityworlds                     | 1.1.0            | UtilityWorlds-1.12.2_1.1.0.jar                      | None                                     |
       | UCH   | universalmodifiers                | 1.12.2-1.0.16.1  | valkyrielib-1.12.2-2.0.20.1.jar                     | None                                     |
       | UCH   | vanillafix                        | 1.0.10-SNAPSHOT  | VanillaFix-1.0.10-99.jar                            | None                                     |
       | UCH   | totemexpansion                    | 1.2.2            | totemexpansion-1.2.2-1.12.2.jar                     | None                                     |
       | UCH   | teslacorelib_registries           | 1.0.15           | tesla-core-lib-1.12.2-1.0.15.jar                    | None                                     |
       | UCH   | wrapup                            | 1.12-1.1.3       | WrapUp-1.12-1.1.3.jar                               | None                                     |
  Loaded coremods (and transformers): EnderCorePlugin (EnderCore-1.12.2-0.5.52-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      HCASM (HammerCore-1.12.2-2.0.4.4.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      ForgelinPlugin (Forgelin-1.6.0.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      EECore (ExpandedEquivalence-1.12.2-11b.jar)
                                        com.zeitheron.expequiv.core.EETransformer
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4400'
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 579 names; 815 stacks.
                           Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Equivalent Additions (equivadditions) @5r
                               -Expanded Equivalence (expequiv) @11b
                               -Improvable Skills (improvableskills) @3.6.2r
                               -Solar Flux Additions (wearsfr) @17r
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.13.3.416
              Runtime Debofucsation 1
              RenderEngine: 1
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Random Enchantments (randomenchantments)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4835, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer o

**Comment by Tfarcenim** [comment]
update forge
