### ISSUE TITLE
java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank

### ISSUE THREAD

**Issue by Erdnussflip007** [Tfarcenim/RandomEnchantments#47]
The game just crashes before it fully loads. This issue doesn't only aplly to mekanism, but several other mods, like netherEx aswell.

To replicate just try to start the game with mekanism and RandomEnchantments.

[This](https://pastebin.ubuntu.com/p/MpXTKk3fyX/) is a log where this happened.

**Comment by Tfarcenim** [comment]
Missing additional events
