### ISSUE TITLE
Unknown error caused by Back to the Chamber

### ISSUE THREAD

**Issue by Mattort** [Tfarcenim/RandomEnchantments#5]
I've been getting an error for awhile now and when I look at the crash report it seems like the Back to the Chamber enchant from your mod keeps causing it. It goes away and my game loads fine if I remove your mod from my pack. Here's the link to the crash report:

https://paste.dimdev.org/ixizetufaj.mccrash

I'm fairly certain I'm using the latest version of forge unless one has come up without me knowing.

**Comment by Tfarcenim** [comment]
Delete the config file and let the mod regenerate it

**Comment by Mattort** [comment]
I tried that and it worked. Maybe pin this for any future occurrences?

**Comment by Tfarcenim** [comment]
this is no longer relevant in the newer versions
