### ISSUE TITLE
Instant Kill enchant causes game to not recognize kills.

### ISSUE THREAD

**Issue by Cwoodyard** [Tfarcenim/RandomEnchantments#50]
Heyo, been working on a 1.15.2 forge modpack (client version included below) but it was found that if a user or named entity is killed by a sword (at least) with the enchant, it will not properly list as a kill and not have the kill logged in chat or trigger the pack's gravestone mod.

Mod Version: 3.1.1
Forge: 31.2.45
[ClientVerMana-1.0.3.zip](https://github.com/Tfarcenim/RandomEnchantments/files/5609949/ClientVerMana-1.0.3.zip)

**Comment by Cwoodyard** [comment]
Updated the pack to
[ClientVerMana-1.0.4.zip](https://github.com/Tfarcenim/RandomEnchantments/files/5655996/ClientVerMana-1.0.4.zip)
 delete a mod.

**Comment by smallerYeet** [comment]
This is also present in 1.16.3 and the latest version of the mod.
My Friend just lost all his Items bc I killed him with this enchantment

**Comment by Tfarcenim** [comment]
fixed in 4.0.6
