### ISSUE TITLE
Can't enchant bow with exploding 1

### ISSUE THREAD

**Issue by sergeant-reapor** [Tfarcenim/RandomEnchantments#51]
Title says it all, I can't enchant a bow with exploding 1.  I first tried with a bow that has infinity on it, didn't work. tried it with a non-enchanted bow, still doesn't work. Am I missing something?

![image](https://user-images.githubusercontent.com/76183056/102539529-a8544600-4062-11eb-805d-a19ebb695c91.png)

![image](https://user-images.githubusercontent.com/76183056/102539559-b1451780-4062-11eb-83e7-f0cbc4fa09c9.png)

**Comment by democat3457** [comment]
the tooltip you sent a screenshot of shows the enchantment from DungeonTactics. it's likely one of their scroll enchantments

**Comment by Tfarcenim** [comment]
wrong mod
