### ISSUE TITLE
[suggestion] Elytra specific enchantment that reduces drag/air resistance

### ISSUE THREAD

**Issue by xkforce** [Tfarcenim/RandomEnchantments#6]
The effect of the enchantment would be to reduce the rate that the player falls while traveling at a given angle.  i.e. if the player were level with the horizon, they would fall a fraction of the normal rate based on enchantment level.  You could also combine this with reduced air resistance which would have the effect of increasing the maximum and cruising speeds for the elytra.

**Comment by Tfarcenim** [comment]
putting this on hold because while it would be nice, idk if it can fit within the current scope or if it's even possible without hacking.

**Comment by Tfarcenim** [comment]
just checked, it's currently impossible without coremodding so that's a no.
