### ISSUE TITLE
[Request] Don't reset mining progress when repairing solar tools

### ISSUE THREAD

**Issue by chimericdream** [Tfarcenim/RandomEnchantments#60]
I have Solar V on all of my tools, and it's super handy. But one thing that bugs me is when my tool is repairing itself while I am trying to mine a block with high hardness (ancient debris, obsidian, etc). I don't know exactly what changes within the metadata of the tool, but every second or so until it is fully repaired, the progress mining the current block is reset. Is this something that can be worked around, or should that be treated as part of the trade-off of the Solar enchant?

Thanks!

**Comment by Tfarcenim** [comment]
It's the tradeoff, I don't wish to hack every item to support this behavior.
