### ISSUE TITLE
[1.12.2] Obsidian Buster does not work on Chisel Variants of Obsidian

### ISSUE THREAD

**Issue by marcobsidian** [Tfarcenim/RandomEnchantments#65]
Hiya so I don't think it would be a big issue but could you maybe allow the Obsidian Buster Enchantment to work on the Obsidian Variants introduced by Chisel?

The easiest way of doing that would probably be via the commonly used OreDict tag "obsidian" instead of only working on vanilla obsidian.

I really like the mod otherwise and I hope you're keeping up the good work :)

**Comment by Tfarcenim** [comment]
Thanks for the report, but I'm not doing non-critical bugfixes for any mc version before 1.16.5, however if a pull request is submitted I would be more than happy to make a new release based on that.
