### ISSUE TITLE
Bug with negative durability items, like a half-full Tough as Nails canteen.

### ISSUE THREAD

**Issue by roccscout** [Tfarcenim/RandomEnchantments#72]
There is a seriously annoying bug with this mod installed--

If there is an item with negative durability that is never supposed to break, like Tough as Nails Canteens, they will break if left-clicked on something like grass or flowers with Random Enchants installed.

I'm not sure why Random Enchants does this, but if you accidentally swing something like a half-full canteen through grass, the canteen will "break" likely due to the "negative durability" it has.

Why this mod, though? No idea.

**Comment by Tfarcenim** [comment]
Curious, have you verified with only random enchants + TAN?

**Comment by roccscout** [comment]
Yep, just confirmed it. 

If you install _ONLY_ **RandomEnchants** and **TAN**, then:

1)` /give [playername] toughasnails:canteen 1 5`
2) use this 2/3 full canteen to "break" any block, like grass or dirt or wood, the canteen is instantly destroyed. Likely because of how TAN handles their canteens with "negative" durability, maybe.

**Comment by roccscout** [comment]
I'm releasing a huge modpack after 1.5 years of work, but I might need to wait until this can (hopefully, fingers crossed!) get patched!
