### ISSUE TITLE
1.12.2 Random Enchantment ID #s change on a game-to-game basis.

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/RandomEnchantments#73]
Title.

A number of other mods **_completely rely_** on Enchantment ID's to function properly.

I was pulling my hair out trying to figure out why these scrips kept producing incorrect enchantments until I realized RandomEnchants changes the ID of the enchantments constantly.

Any way to get Enchantment ID's to stay consistent? I have 4 other mods that also add enchantments, but this one is the only one that changes ID numbers consistently.

**Comment by Tfarcenim** [comment]
No, this is a flaw of 1.12 Minecraft as it stores enchantments as raw IDs instead of resource locations, this has been fixed in 1.13+, but there is nothing I can do.
