### ISSUE TITLE
Homing Enchant One-Shotting Mobs

### ISSUE THREAD

**Issue by bench-wench** [Tfarcenim/RandomEnchantments#9]
The Homing enchant for the bow is currently overpowered as it one shots mobs. This is due to minecraft calculating damage based off of arrow speed. The arrow gains a crazy amount of speed when it nears a mob with this enchant. I have done some tinkering for the enchant. It basically slows the arrow down when it locks onto an entity, then right before it hits the entity it speeds back up to a normal speed which brings the damage back to normal numbers.

@SubscribeEvent
  public void serverTick(TickEvent.ServerTickEvent e)
  {
    if (e.phase != TickEvent.Phase.END) return;
    List<EntityArrow> removeHoming = new ArrayList<>();
    for (EntityArrow arrow : homingarrows)
    {
    	if (arrow.ticksExisted > 400 || arrow.isDead)
    	{
    		arrow.setDead();removeHoming.add(arrow);continue;
    	}
    	World world = arrow.world;
    	int r = 6;
    	double x = arrow.posX;
    	double y = arrow.posY;
    	double z = arrow.posZ;
    	List<Entity> targets = world.getEntitiesWithinAABB(EntityLivingBase.class, new AxisAlignedBB(x - r, y - r, z - r, x + r, y + r, z + r));
    	if (targets.size() == 0) continue;
    	for (Entity target : targets)
    	{
    		if (target instanceof EntityPlayer || target instanceof EntityEnderman || target instanceof EntityAnimal)
    		continue;
    		double speed = 0.2; // SPEED OF ARROW WHEN IT LOCKS ON TO A TARGET
    		if ( Math.abs(target.posX - arrow.posX) + Math.abs(target.posZ - arrow.posZ) < 4 ) // IF THE ARROW IS CLOSE TO A TARGET, THEN...
    		{
    			speed = 1; // SET THE ARROW SPEED TO A FIXED VALUE (normalizes damage)
    		}
    		AxisAlignedBB box = target.getEntityBoundingBox();
    		double diff = box.maxY - box.minY;
    		Vec3d arrowDirection = new Vec3d(target.posX - arrow.posX,target.posY + diff - arrow.posY, target.posZ - arrow.posZ);
    		normalize(arrowDirection);
    		arrow.setVelocity(speed * arrowDirection.x, speed * arrowDirection.y, speed * arrowDirection.z);
    		arrow.velocityChanged = true;
    	}
    }
    homingarrows.removeAll(removeHoming);
  }

**Comment by Tfarcenim** [comment]
fixed in 0.0.11a
